version: '3.8'

services:
  pi-hmarl:
    build:
      context: .
      dockerfile: Dockerfile
    image: pi-hmarl:latest
    container_name: pi-hmarl-dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - WANDB_API_KEY=${WANDB_API_KEY}
      - PYTHONPATH=/workspace/pi-hmarl
    volumes:
      - .:/workspace/pi-hmarl
      - ${HOME}/.cache:/root/.cache
      - pi-hmarl-experiments:/workspace/pi-hmarl/experiments
      - pi-hmarl-data:/workspace/pi-hmarl/data
    ports:
      - "6006:6006"  # TensorBoard
      - "8265:8265"  # Ray Dashboard
      - "8888:8888"  # Jupyter Notebook
    shm_size: '16gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    command: /bin/bash

  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: pi-hmarl:latest
    container_name: pi-hmarl-tensorboard
    volumes:
      - ./experiments:/workspace/pi-hmarl/experiments:ro
    ports:
      - "6007:6006"
    command: tensorboard --logdir=/workspace/pi-hmarl/experiments --host=0.0.0.0

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: pi-hmarl:latest
    container_name: pi-hmarl-jupyter
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace/pi-hmarl
      - ${HOME}/.cache:/root/.cache
    ports:
      - "8889:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

volumes:
  pi-hmarl-experiments:
  pi-hmarl-data:
EOF < /dev/null