# Default configuration for PI-HMARL
# Real-Parameter Synthetic Data Strategy Configuration

experiment:
  name: "pi_hmarl_experiment"
  project: "pi-hmarl"
  tags: ["multi-agent", "physics-informed", "hierarchical"]
  notes: "Physics-Informed Hierarchical Multi-Agent RL with Real-Parameter Synthetic Data"
  log_dir: "./experiments"
  wandb_entity: null
  wandb_project: "pi-hmarl"
  save_frequency: 1000
  checkpoint_frequency: 5000

training:
  algorithm: "PI-HMARL"
  num_agents: 10
  max_episodes: 10000
  max_steps_per_episode: 1000
  batch_size: 256
  learning_rate: 0.0003
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  warmup_steps: 10000
  update_frequency: 4
  gradient_clip: 1.0
  num_workers: 4
  use_gpu: true
  seed: 42
  
  # Real-Parameter Synthetic Data Strategy
  data_strategy: "real_parameter_synthetic"
  synthetic_data_ratio: 0.85
  real_validation_ratio: 0.15
  synthetic_scenarios: 10000
  
physics:
  engine: "pybullet"
  timestep: 0.01
  gravity: [0.0, 0.0, -9.81]
  enable_collision: true
  enable_energy_constraints: true
  enable_dynamics_constraints: true
  max_velocity: 20.0  # m/s
  max_acceleration: 10.0  # m/s^2
  min_separation_distance: 2.0  # meters
  energy_penalty_weight: 0.1
  physics_loss_weight: 0.3
  
  # Real-world physics parameters
  real_parameters:
    # DJI Mavic 3 specifications
    drone_mass: 0.895  # kg
    max_flight_speed: 19.0  # m/s
    max_ascent_speed: 8.0  # m/s
    max_descent_speed: 6.0  # m/s
    battery_capacity: 5000  # mAh
    flight_time: 46  # minutes
    
    # Aerodynamic parameters
    drag_coefficient: 0.47
    frontal_area: 0.06  # m^2
    
    # Motor specifications
    motor_efficiency: 0.85
    propeller_efficiency: 0.8
    
agent:
  observation_dim: 64
  action_dim: 4
  hidden_dims: [256, 256]
  attention_heads: 8
  attention_dim: 64
  use_hierarchical: true
  meta_controller_update_freq: 10
  skill_duration: 5
  communication_range: 50.0  # meters
  sensor_range: 30.0  # meters
  battery_capacity: 5000.0  # mAh
  max_speed: 19.0  # m/s (DJI Mavic 3 spec)
  mass: 0.895  # kg (DJI Mavic 3 spec)
  
  # Hierarchical architecture
  meta_controller:
    type: "MAPPO"
    update_frequency: 10
    planning_horizon: 60  # seconds
    
  execution_policy:
    type: "DQN"
    control_frequency: 50  # Hz
    
# Real-Parameter Sources
real_parameter_sources:
  drone_specifications:
    - "DJI Mavic 3"
    - "Parrot ANAFI"
    - "Autel EVO II"
    
  battery_data:
    - "Samsung INR18650-25R"
    - "LG HG2 18650"
    
  communication_specs:
    - "WiFi 802.11ac"
    - "5G NR"
    
  weather_data:
    - "NOAA historical wind patterns"
    - "Local weather station data"
EOF < /dev/null