# Physics-Informed Neural Network Configuration
# Based on real physics parameters and constraints

pinn:
  # Base network configuration
  network:
    type: "residual"  # standard, constrained, residual
    input_dim: 12  # State dimension
    hidden_dims: [128, 128, 128]
    output_dim: 12  # Next state dimension
    physics_dim: 12
    activation: "tanh"
    use_batch_norm: false
    dropout: 0.0
    physics_weight: 1.0
    
  # Automatic differentiation settings
  autodiff:
    enable_second_order: true
    enable_mixed_derivatives: false
    dtype: "float32"
    
  # Port-Hamiltonian configuration
  port_hamiltonian:
    enabled: true
    state_dim: 12  # 6 for position/momentum
    control_dim: 4
    dissipation: true
    external_forces: true
    hidden_dims: [64, 64]
    
    # Real physical parameters
    physics:
      mass: 1.5  # kg (DJI Mavic 3 mass)
      gravity: 9.81  # m/s²
      drag_coefficient: 0.5
      
  # Conservation laws configuration
  conservation_laws:
    enabled: true
    
    # Real dynamics parameters
    dynamics:
      mass: 1.5  # kg
      inertia_tensor: [[0.02, 0.0, 0.0],
                       [0.0, 0.02, 0.0],
                       [0.0, 0.0, 0.03]]  # kg⋅m² (drone inertia)
      gravity: 9.81  # m/s²
      
    # Conservation types
    enforce:
      linear_momentum: true
      angular_momentum: true
      energy: true
      action_reaction: true
      
    # Relativistic corrections
    relativistic:
      enabled: false
      speed_of_light: 299792458.0  # m/s
      
  # Collision constraints configuration
  collision_constraints:
    enabled: true
    
    # Real safety parameters
    safety:
      min_separation: 5.0  # meters (drone safety distance)
      safety_margin: 1.5  # Additional safety factor
      max_agents: 20
      collision_penalty: 100.0
      use_soft_constraints: true
      
    # Time-to-collision
    ttc:
      min_ttc: 3.0  # seconds
      predict_trajectories: true
      horizon: 10  # prediction steps
      
    # Dynamic separation
    dynamic:
      velocity_scale: 0.5  # seconds of lookahead
      potential_scale: 10.0
      
  # Physics loss configuration
  physics_loss:
    # Loss weights
    weights:
      energy_conservation: 1.0
      momentum_conservation: 1.0
      angular_momentum: 0.5
      collision_avoidance: 10.0
      pde_residual: 1.0
      boundary_condition: 1.0
      dissipation_positive: 0.1
      skew_symmetry: 0.1
      kinetic_positive: 0.1
      
    # Adaptive weighting
    adaptive:
      enabled: true
      grad_norm_weighting: false
      uncertainty_weighting: false
      update_frequency: 100
      
    # PDE settings
    pde:
      type: "navier_stokes"  # heat, wave, navier_stokes
      domain_size: [100.0, 100.0, 50.0]  # meters
      coefficients:
        viscosity: 0.01
        density: 1.225  # kg/m³ (air density)
        diffusivity: 0.1
        
    # Boundary conditions
    boundary:
      type: "dirichlet"  # dirichlet, neumann, robin, periodic
      weight: 100.0
      
  # Constraint embedding configuration
  constraint_embedding:
    enabled: true
    input_dim: 12
    constraint_dim: 32
    hidden_dim: 128
    num_constraints: 5
    use_attention: true
    
    # Constraint types
    constraints:
      - "energy"
      - "momentum" 
      - "collision"
      - "boundary"
      - "continuity"
      
  # Multi-fidelity configuration
  multi_fidelity:
    enabled: true
    num_levels: 3
    correlation_type: "nonlinear"  # linear, nonlinear
    adaptive_sampling: true
    
    # Fidelity levels
    levels:
      - name: "low"
        cost: 1.0
        accuracy: 0.7
      - name: "medium"
        cost: 10.0
        accuracy: 0.9
      - name: "high"
        cost: 100.0
        accuracy: 0.99
        
    # Uncertainty quantification
    uncertainty:
      type: "combined"  # aleatoric, epistemic, combined
      num_samples: 10
      
    # Co-Kriging settings
    cokriging:
      kernel_type: "rbf"  # rbf, matern
      num_inducing_points: 100
      
# Training configuration
training:
  # Optimization
  optimizer:
    type: "adam"
    lr: 0.001
    weight_decay: 0.0001
    
  # Learning rate schedule
  scheduler:
    type: "cosine"
    warmup_steps: 1000
    min_lr: 0.00001
    
  # Training parameters
  batch_size: 64
  num_epochs: 1000
  gradient_clip: 1.0
  
  # Physics-informed training
  physics_training:
    collocation_points: 1000
    boundary_points: 200
    initial_points: 100
    
  # Curriculum learning
  curriculum:
    enabled: true
    start_physics_weight: 0.1
    end_physics_weight: 1.0
    increase_every: 100  # epochs
    
# Validation configuration
validation:
  # Physics validation
  check_conservation: true
  check_stability: true
  check_constraints: true
  
  # Analytical solutions
  analytical_tests:
    - "harmonic_oscillator"
    - "free_fall"
    - "circular_motion"
    
  # Tolerance
  conservation_tolerance: 0.01
  constraint_tolerance: 0.001
  
# Inference configuration
inference:
  # Integration method
  integrator: "symplectic_euler"  # symplectic_euler, leapfrog, rk4
  dt: 0.01  # seconds
  
  # Constraint projection
  project_constraints: true
  projection_steps: 10
  projection_step_size: 0.1